### ISSUE TITLE
Default quality range

### ISSUE THREAD

**Issue by kornelski** [psych0der/pngquantjs#2]
Thanks for making it work!

When I've tried it, the quality range I got was 30-35. 

I recommend always setting max quality to 100, since filesize reduction from quality < 100 isn't very large, but has a potential to introduce visible degradation.

You could even use 0-100 range by default, which would mean everything is always converted to 256 colors, which is OK for pngquant-only tool without a fallback to another format.

**Comment by psych0der** [comment]
Yes, I agree. 30-35 was the range I got from testing various images, so I thought to make it as default. Well, 0-100 seems fine too, I'll update it.
